import { Router } from 'express';
import { authenticate, requirePermission } from '../identity/middleware';
import { validateRequest } from '../../middleware/validate';
import { inventoryController } from './controller';
import { adjustmentSchema, confirmCountSchema, createCategorySchema, createCountSchema, createItemSchema, createLocationSchema, inventoryListQuerySchema, movementListQuerySchema, openingStockSchema, transferSchema, updateCategorySchema, updateItemSchema, updateLocationSchema } from './validation';

export const inventoryRouter=Router();
inventoryRouter.use(authenticate());
const view=requirePermission('inventory:view','inventory:history:view');
const manage=requirePermission('inventory:manage');
inventoryRouter.get('/units',view,inventoryController.units);
inventoryRouter.get('/overview',view,inventoryController.overview);
inventoryRouter.get('/categories',view,inventoryController.categories);
inventoryRouter.post('/categories',requirePermission('inventory:categories:manage'),validateRequest({body:createCategorySchema}),inventoryController.createCategory);
inventoryRouter.patch('/categories/:id',requirePermission('inventory:categories:manage'),validateRequest({body:updateCategorySchema}),inventoryController.updateCategory);
inventoryRouter.get('/locations',view,inventoryController.locations);
inventoryRouter.post('/locations',requirePermission('inventory:locations:manage'),validateRequest({body:createLocationSchema}),inventoryController.createLocation);
inventoryRouter.patch('/locations/:id',requirePermission('inventory:locations:manage'),validateRequest({body:updateLocationSchema}),inventoryController.updateLocation);
inventoryRouter.get('/items',view,validateRequest({query:inventoryListQuerySchema}),inventoryController.items);
inventoryRouter.post('/items',requirePermission('inventory:items:manage'),validateRequest({body:createItemSchema}),inventoryController.createItem);
inventoryRouter.get('/items/:id',view,inventoryController.getItem);
inventoryRouter.patch('/items/:id',requirePermission('inventory:items:manage'),validateRequest({body:updateItemSchema}),inventoryController.updateItem);
inventoryRouter.get('/stock',view,inventoryController.stock);
inventoryRouter.get('/stock/:itemId',view,inventoryController.itemStock);
inventoryRouter.post('/opening-stock',requirePermission('inventory:opening:manage'),validateRequest({body:openingStockSchema}),inventoryController.opening);
inventoryRouter.post('/adjustments',requirePermission('inventory:adjust'),validateRequest({body:adjustmentSchema}),inventoryController.adjustment);
inventoryRouter.post('/transfers',requirePermission('inventory:transfer'),validateRequest({body:transferSchema}),inventoryController.transfer);
inventoryRouter.get('/movements',requirePermission('inventory:history:view','inventory:view'),validateRequest({query:movementListQuerySchema}),inventoryController.movements);
inventoryRouter.get('/counts',requirePermission('inventory:count','inventory:view'),inventoryController.counts);
inventoryRouter.post('/counts',requirePermission('inventory:count'),validateRequest({body:createCountSchema}),inventoryController.createCount);
inventoryRouter.get('/counts/:id',requirePermission('inventory:count','inventory:view'),inventoryController.getCount);
inventoryRouter.post('/counts/:id/confirm',requirePermission('inventory:count'),validateRequest({body:confirmCountSchema}),inventoryController.confirmCount);
