import { Request, Response, NextFunction } from 'express';
import { ApiSuccessResponse } from '../../shared/types';
import { BadRequestError, ForbiddenError } from '../../shared/errors';
import { recipeRepository } from './repository';
import { realtimePublisher } from '../../realtime/publisher';

function context(req: Request) {
  if (!req.user?.organizationId) throw new ForbiddenError('Authenticated tenant context is missing', 'MISSING_TENANT_CONTEXT');
  if (!req.user.activeBranchId) throw new ForbiddenError('Active branch context is missing', 'MISSING_BRANCH_CONTEXT');
  return { organizationId: req.user.organizationId, branchId: req.user.activeBranchId, userId: req.user.id };
}
function id(value: unknown, label: string) {
  const parsed = Number(value);
  if (!Number.isInteger(parsed) || parsed <= 0) throw new BadRequestError(`Valid ${label} ID is required`, `INVALID_${label.toUpperCase().replace(/\W+/g, '_')}_ID`);
  return parsed;
}

export class RecipeController {
  list = async (req: Request, res: Response, next: NextFunction) => { try { const c=context(req); res.json({success:true,data:await recipeRepository.list(c.organizationId,c.branchId,req.query)} satisfies ApiSuccessResponse); } catch(e){next(e);} };
  get = async (req: Request, res: Response, next: NextFunction) => { try { const c=context(req); res.json({success:true,data:await recipeRepository.get(c.organizationId,c.branchId,id(req.params.id,'recipe'))} satisfies ApiSuccessResponse); } catch(e){next(e);} };
  create = async (req: Request, res: Response, next: NextFunction) => { try { const c=context(req); const recipe=await recipeRepository.create(c.organizationId,c.branchId,c.userId,req.body); realtimePublisher.publish({type:'recipe.created',organizationId:c.organizationId,branchId:c.branchId,entityType:'recipe',entityId:recipe.id,data:{menuItemId:recipe.menuItemId,status:recipe.status}}); res.status(201).json({success:true,data:recipe} satisfies ApiSuccessResponse); } catch(e){next(e);} };
  update = async (req: Request, res: Response, next: NextFunction) => { try { const c=context(req); const recipeId=id(req.params.id,'recipe'); const recipe=await recipeRepository.update(c.organizationId,c.branchId,recipeId,req.body); realtimePublisher.publish({type:'recipe.updated',organizationId:c.organizationId,branchId:c.branchId,entityType:'recipe',entityId:recipeId,data:{menuItemId:recipe.menuItemId,status:recipe.status}}); res.json({success:true,data:recipe} satisfies ApiSuccessResponse); } catch(e){next(e);} };
  archive = async (req: Request, res: Response, next: NextFunction) => { try { const c=context(req); const recipeId=id(req.params.id,'recipe'); const recipe=await recipeRepository.archive(c.organizationId,c.branchId,recipeId); realtimePublisher.publish({type:'recipe.archived',organizationId:c.organizationId,branchId:c.branchId,entityType:'recipe',entityId:recipeId,data:{menuItemId:recipe.menuItemId,status:recipe.status}}); res.json({success:true,data:recipe} satisfies ApiSuccessResponse); } catch(e){next(e);} };
  versions = async (req: Request, res: Response, next: NextFunction) => { try { const c=context(req); res.json({success:true,data:await recipeRepository.versions(c.organizationId,c.branchId,id(req.params.id,'recipe'))} satisfies ApiSuccessResponse); } catch(e){next(e);} };
  createVersion = async (req: Request, res: Response, next: NextFunction) => { try { const c=context(req); res.status(201).json({success:true,data:await recipeRepository.createVersion(c.organizationId,c.branchId,id(req.params.id,'recipe'),c.userId,req.body)} satisfies ApiSuccessResponse); } catch(e){next(e);} };
  updateVersion = async (req: Request, res: Response, next: NextFunction) => { try { const c=context(req); res.json({success:true,data:await recipeRepository.updateVersion(c.organizationId,c.branchId,id(req.params.id,'recipe'),id(req.params.versionId,'version'),req.body)} satisfies ApiSuccessResponse); } catch(e){next(e);} };
  activateVersion = async (req: Request, res: Response, next: NextFunction) => { try { const c=context(req); const recipeId=id(req.params.id,'recipe'); const versionId=id(req.params.versionId,'version'); const recipe=await recipeRepository.activateVersion(c.organizationId,c.branchId,recipeId,versionId); realtimePublisher.publish({type:'recipe.version_activated',organizationId:c.organizationId,branchId:c.branchId,entityType:'recipe',entityId:recipeId,data:{versionId,versionNumber:recipe.versions.find((v:any)=>v.id===versionId)?.versionNumber ?? null}}); realtimePublisher.publish({type:'recipe.cost_changed',organizationId:c.organizationId,branchId:c.branchId,entityType:'recipe',entityId:recipeId,data:{reason:'RECIPE_VERSION_ACTIVATED'}}); res.json({success:true,data:recipe} satisfies ApiSuccessResponse); } catch(e){next(e);} };
  addIngredient = async (req: Request, res: Response, next: NextFunction) => { try { const c=context(req); const recipeId=id(req.params.id,'recipe'); const data=await recipeRepository.addIngredient(c.organizationId,c.branchId,recipeId,id(req.params.versionId,'version'),req.body); realtimePublisher.publish({type:'recipe.cost_changed',organizationId:c.organizationId,branchId:c.branchId,entityType:'recipe',entityId:recipeId,data:{reason:'INGREDIENT_ADDED'}}); res.status(201).json({success:true,data} satisfies ApiSuccessResponse); } catch(e){next(e);} };
  updateIngredient = async (req: Request, res: Response, next: NextFunction) => { try { const c=context(req); const recipeId=id(req.params.id,'recipe'); const data=await recipeRepository.updateIngredient(c.organizationId,c.branchId,recipeId,id(req.params.versionId,'version'),id(req.params.ingredientId,'ingredient'),req.body); realtimePublisher.publish({type:'recipe.cost_changed',organizationId:c.organizationId,branchId:c.branchId,entityType:'recipe',entityId:recipeId,data:{reason:'INGREDIENT_UPDATED'}}); res.json({success:true,data} satisfies ApiSuccessResponse); } catch(e){next(e);} };
  deleteIngredient = async (req: Request, res: Response, next: NextFunction) => { try { const c=context(req); const recipeId=id(req.params.id,'recipe'); const data=await recipeRepository.deleteIngredient(c.organizationId,c.branchId,recipeId,id(req.params.versionId,'version'),id(req.params.ingredientId,'ingredient')); realtimePublisher.publish({type:'recipe.cost_changed',organizationId:c.organizationId,branchId:c.branchId,entityType:'recipe',entityId:recipeId,data:{reason:'INGREDIENT_DELETED'}}); res.json({success:true,data} satisfies ApiSuccessResponse); } catch(e){next(e);} };
  cost = async (req: Request, res: Response, next: NextFunction) => { try { const c=context(req); const versionId=req.query.versionId? id(req.query.versionId,'version'):undefined; res.json({success:true,data:await recipeRepository.cost(c.organizationId,c.branchId,id(req.params.id,'recipe'),versionId)} satisfies ApiSuccessResponse); } catch(e){next(e);} };
  menuItemCosting = async (req: Request, res: Response, next: NextFunction) => { try { const c=context(req); res.json({success:true,data:await recipeRepository.menuItemCosting(c.organizationId,c.branchId,id(req.params.menuItemId,'menu item'))} satisfies ApiSuccessResponse); } catch(e){next(e);} };
  directStock = async (req: Request, res: Response, next: NextFunction) => { try { const c=context(req); res.json({success:true,data:await recipeRepository.getDirectStockLink(c.organizationId,c.branchId,id(req.params.menuItemId,'menu item'))} satisfies ApiSuccessResponse); } catch(e){next(e);} };
  setDirectStock = async (req: Request, res: Response, next: NextFunction) => { try { const c=context(req); res.json({success:true,data:await recipeRepository.setDirectStockLink(c.organizationId,c.branchId,id(req.params.menuItemId,'menu item'),req.body)} satisfies ApiSuccessResponse); } catch(e){next(e);} };
  modifierImpacts = async (req: Request, res: Response, next: NextFunction) => { try { const c=context(req); res.json({success:true,data:await recipeRepository.modifierImpacts(c.organizationId,c.branchId,id(req.params.optionId,'modifier option'))} satisfies ApiSuccessResponse); } catch(e){next(e);} };
  setModifierImpacts = async (req: Request, res: Response, next: NextFunction) => { try { const c=context(req); res.json({success:true,data:await recipeRepository.replaceModifierImpacts(c.organizationId,c.branchId,id(req.params.optionId,'modifier option'),req.body.impacts)} satisfies ApiSuccessResponse); } catch(e){next(e);} };
  variantImpacts = async (req: Request, res: Response, next: NextFunction) => { try { const c=context(req); res.json({success:true,data:await recipeRepository.variantImpacts(c.organizationId,c.branchId,id(req.params.variantId,'variant'))} satisfies ApiSuccessResponse); } catch(e){next(e);} };
  setVariantImpacts = async (req: Request, res: Response, next: NextFunction) => { try { const c=context(req); res.json({success:true,data:await recipeRepository.replaceVariantImpacts(c.organizationId,c.branchId,id(req.params.variantId,'variant'),req.body.impacts)} satisfies ApiSuccessResponse); } catch(e){next(e);} };
}
export const recipeController = new RecipeController();
