import { Request, Response, NextFunction } from 'express';
import { ApiSuccessResponse } from '../../shared/types';
import { BadRequestError, ForbiddenError } from '../../shared/errors';
import { inventoryRepository } from './repository';
function ctx(req: Request){ if(!req.user?.organizationId) throw new ForbiddenError('Authenticated tenant context is missing','MISSING_TENANT_CONTEXT'); if(!req.user.activeBranchId) throw new ForbiddenError('Active branch context is missing','MISSING_BRANCH_CONTEXT'); return {orgId:req.user.organizationId,branchId:req.user.activeBranchId,userId:req.user.id}; }
function id(v:any,label:string){const n=Number(v);if(!Number.isInteger(n)||n<=0)throw new BadRequestError(`Valid ${label} is required`,`INVALID_${label.toUpperCase().replace(/[^A-Z]+/g,'_')}_ID`);return n;}
export class InventoryController {
  units=async(req:Request,res:Response,next:NextFunction)=>{try{const c=ctx(req);res.json({success:true,data:await inventoryRepository.listUnits(c.orgId)} satisfies ApiSuccessResponse<any>)}catch(e){next(e)}};
  categories=async(req:Request,res:Response,next:NextFunction)=>{try{const c=ctx(req);res.json({success:true,data:await inventoryRepository.listCategories(c.orgId,c.branchId)} satisfies ApiSuccessResponse<any>)}catch(e){next(e)}};
  createCategory=async(req:Request,res:Response,next:NextFunction)=>{try{const c=ctx(req);res.status(201).json({success:true,data:await inventoryRepository.createCategory(c.orgId,c.branchId,req.body)} satisfies ApiSuccessResponse<any>)}catch(e){next(e)}};
  updateCategory=async(req:Request,res:Response,next:NextFunction)=>{try{const c=ctx(req);res.json({success:true,data:await inventoryRepository.updateCategory(c.orgId,c.branchId,id(req.params.id,'category'),req.body)} satisfies ApiSuccessResponse<any>)}catch(e){next(e)}};
  locations=async(req:Request,res:Response,next:NextFunction)=>{try{const c=ctx(req);res.json({success:true,data:await inventoryRepository.listLocations(c.orgId,c.branchId)} satisfies ApiSuccessResponse<any>)}catch(e){next(e)}};
  createLocation=async(req:Request,res:Response,next:NextFunction)=>{try{const c=ctx(req);res.status(201).json({success:true,data:await inventoryRepository.createLocation(c.orgId,c.branchId,req.body)} satisfies ApiSuccessResponse<any>)}catch(e){next(e)}};
  updateLocation=async(req:Request,res:Response,next:NextFunction)=>{try{const c=ctx(req);res.json({success:true,data:await inventoryRepository.updateLocation(c.orgId,c.branchId,id(req.params.id,'location'),req.body)} satisfies ApiSuccessResponse<any>)}catch(e){next(e)}};
  items=async(req:Request,res:Response,next:NextFunction)=>{try{const c=ctx(req);res.json({success:true,data:await inventoryRepository.listItems(c.orgId,c.branchId,req.query)} satisfies ApiSuccessResponse<any>)}catch(e){next(e)}};
  getItem=async(req:Request,res:Response,next:NextFunction)=>{try{const c=ctx(req);const item=await inventoryRepository.getItem(c.orgId,c.branchId,id(req.params.id,'item'));if(!item)throw new BadRequestError('Inventory item not found','INVENTORY_ITEM_NOT_FOUND');res.json({success:true,data:item} satisfies ApiSuccessResponse<any>)}catch(e){next(e)}};
  createItem=async(req:Request,res:Response,next:NextFunction)=>{try{const c=ctx(req);res.status(201).json({success:true,data:await inventoryRepository.createItem(c.orgId,c.branchId,req.body)} satisfies ApiSuccessResponse<any>)}catch(e){next(e)}};
  updateItem=async(req:Request,res:Response,next:NextFunction)=>{try{const c=ctx(req);res.json({success:true,data:await inventoryRepository.updateItem(c.orgId,c.branchId,id(req.params.id,'item'),req.body)} satisfies ApiSuccessResponse<any>)}catch(e){next(e)}};
  stock=async(req:Request,res:Response,next:NextFunction)=>{try{const c=ctx(req);res.json({success:true,data:await inventoryRepository.listStock(c.orgId,c.branchId,req.query)} satisfies ApiSuccessResponse<any>)}catch(e){next(e)}};
  itemStock=async(req:Request,res:Response,next:NextFunction)=>{try{const c=ctx(req);res.json({success:true,data:await inventoryRepository.getStockForItem(c.orgId,c.branchId,id(req.params.itemId,'inventory item'))} satisfies ApiSuccessResponse<any>)}catch(e){next(e)}};
  opening=async(req:Request,res:Response,next:NextFunction)=>{try{const c=ctx(req);res.status(201).json({success:true,data:await inventoryRepository.openingStock(c.orgId,c.branchId,req.body,c.userId)} satisfies ApiSuccessResponse<any>)}catch(e){next(e)}};
  adjustment=async(req:Request,res:Response,next:NextFunction)=>{try{const c=ctx(req);res.status(201).json({success:true,data:await inventoryRepository.adjustment(c.orgId,c.branchId,req.body,c.userId)} satisfies ApiSuccessResponse<any>)}catch(e){next(e)}};
  transfer=async(req:Request,res:Response,next:NextFunction)=>{try{const c=ctx(req);res.status(201).json({success:true,data:await inventoryRepository.transfer(c.orgId,c.branchId,req.body,c.userId)} satisfies ApiSuccessResponse<any>)}catch(e){next(e)}};
  movements=async(req:Request,res:Response,next:NextFunction)=>{try{const c=ctx(req);res.json({success:true,data:await inventoryRepository.movements(c.orgId,c.branchId,req.query)} satisfies ApiSuccessResponse<any>)}catch(e){next(e)}};
  createCount=async(req:Request,res:Response,next:NextFunction)=>{try{const c=ctx(req);res.status(201).json({success:true,data:await inventoryRepository.createCount(c.orgId,c.branchId,Number(req.body.locationId),req.body.itemIds,c.userId,req.body.notes)} satisfies ApiSuccessResponse<any>)}catch(e){next(e)}};
  counts=async(req:Request,res:Response,next:NextFunction)=>{try{const c=ctx(req);res.json({success:true,data:await inventoryRepository.listCounts(c.orgId,c.branchId)} satisfies ApiSuccessResponse<any>)}catch(e){next(e)}};
  getCount=async(req:Request,res:Response,next:NextFunction)=>{try{const c=ctx(req);const data=await inventoryRepository.getCount(c.orgId,c.branchId,id(req.params.id,'count'));if(!data)throw new BadRequestError('Stock count not found','INVENTORY_COUNT_NOT_FOUND');res.json({success:true,data} satisfies ApiSuccessResponse<any>)}catch(e){next(e)}};
  confirmCount=async(req:Request,res:Response,next:NextFunction)=>{try{const c=ctx(req);res.json({success:true,data:await inventoryRepository.confirmCount(c.orgId,c.branchId,id(req.params.id,'count'),c.userId,req.body.items)} satisfies ApiSuccessResponse<any>)}catch(e){next(e)}};
  overview=async(req:Request,res:Response,next:NextFunction)=>{try{const c=ctx(req);res.json({success:true,data:await inventoryRepository.overview(c.orgId,c.branchId)} satisfies ApiSuccessResponse<any>)}catch(e){next(e)}};
}
export const inventoryController=new InventoryController();
