import { PoolConnection, ResultSetHeader, RowDataPacket } from 'mysql2/promise';
import { getDatabasePool } from '../../db/pool';
import { BadRequestError, ConflictError, ForbiddenError, NotFoundError } from '../../shared/errors';
import { InventoryBalance, InventoryCategory, InventoryCount, InventoryItem, InventoryLocation, InventoryMovement, InventoryMovementType, InventoryOverview } from './types';

const SCALE = 10000;
const q = (n: number) => Math.round(Number(n) * SCALE) / SCALE;

const iso = (v: any) => v instanceof Date ? v.toISOString() : String(v);
function mapCategory(r: any): InventoryCategory { return { id: Number(r.id), organizationId: Number(r.organization_id), branchId: Number(r.branch_id), name: String(r.name), code: r.code == null ? null : String(r.code), isActive: Boolean(r.is_active), createdAt: iso(r.created_at), updatedAt: iso(r.updated_at) }; }
function mapLocation(r: any): InventoryLocation { return { id: Number(r.id), organizationId: Number(r.organization_id), branchId: Number(r.branch_id), name: String(r.name), code: String(r.code), isActive: Boolean(r.is_active), notes: r.notes == null ? null : String(r.notes), createdAt: iso(r.created_at), updatedAt: iso(r.updated_at) }; }
function mapItem(r: any): InventoryItem { return { id: Number(r.id), organizationId: Number(r.organization_id), branchId: Number(r.branch_id), categoryId: r.category_id == null ? null : Number(r.category_id), categoryName: r.category_name == null ? null : String(r.category_name), unitId: Number(r.unit_id), unitSymbol: String(r.unit_symbol), name: String(r.name), sku: r.sku == null ? null : String(r.sku), costPerUnit: Number(r.cost_per_unit), reorderPoint: Number(r.reorder_point), reorderQuantity: Number(r.reorder_quantity), isActive: Boolean(r.is_active), notes: r.notes == null ? null : String(r.notes), createdAt: iso(r.created_at), updatedAt: iso(r.updated_at) }; }
function mapMovement(r: any): InventoryMovement { return { id: Number(r.id), organizationId: Number(r.organization_id), branchId: Number(r.branch_id), inventoryItemId: Number(r.inventory_item_id), itemName: String(r.item_name), locationId: Number(r.location_id), locationName: String(r.location_name), movementType: r.movement_type, quantity: Number(r.quantity), unitId: Number(r.unit_id), unitSymbol: String(r.unit_symbol), beforeQuantity: Number(r.before_quantity), afterQuantity: Number(r.after_quantity), reason: String(r.reason), referenceType: r.reference_type == null ? null : String(r.reference_type), referenceId: r.reference_id == null ? null : Number(r.reference_id), performedBy: Number(r.performed_by), createdAt: iso(r.created_at) }; }
function stockStatus(current: number, reorderPoint: number): 'OUT_OF_STOCK' | 'LOW_STOCK' | 'IN_STOCK' { if (current <= 0) return 'OUT_OF_STOCK'; if (current <= reorderPoint) return 'LOW_STOCK'; return 'IN_STOCK'; }

export class InventoryRepository {
  pool() { return getDatabasePool(); }

  async assertBranch(orgId: number, branchId: number, conn?: PoolConnection) {
    const db = conn || this.pool();
    const [rows] = await db.execute<RowDataPacket[]>('SELECT id, is_active FROM branches WHERE id = ? AND organization_id = ?', [branchId, orgId]);
    if (!rows.length || !rows[0].is_active) throw new ForbiddenError('Unauthorized or inactive branch', 'UNAUTHORIZED_BRANCH_ACCESS');
  }

  async listUnits(orgId: number) {
    const [rows] = await this.pool().execute<RowDataPacket[]>(`SELECT id, name, symbol, dimension, conversion_factor FROM units_of_measure WHERE is_active = TRUE AND (organization_id IS NULL OR organization_id = ?) ORDER BY dimension, name`, [orgId]);
    return rows.map(r => ({ id: Number(r.id), name: String(r.name), symbol: String(r.symbol), dimension: String(r.dimension), conversionFactor: Number(r.conversion_factor) }));
  }

  async validateUnit(conn: PoolConnection, orgId: number, unitId: number) {
    const [rows] = await conn.execute<RowDataPacket[]>(`SELECT id, symbol, dimension, is_active FROM units_of_measure WHERE id = ? AND is_active = TRUE AND (organization_id IS NULL OR organization_id = ?)`, [unitId, orgId]);
    if (!rows.length) throw new BadRequestError('Invalid or inactive unit of measure', 'INVALID_INVENTORY_UNIT');
    return rows[0];
  }

  async listCategories(orgId: number, branchId: number) { await this.assertBranch(orgId, branchId); const [rows] = await this.pool().execute<RowDataPacket[]>('SELECT * FROM inventory_categories WHERE organization_id = ? AND branch_id = ? ORDER BY is_active DESC, name', [orgId, branchId]); return rows.map(mapCategory); }
  async createCategory(orgId: number, branchId: number, data: any) { await this.assertBranch(orgId, branchId); try { const [r] = await this.pool().execute<ResultSetHeader>('INSERT INTO inventory_categories (organization_id, branch_id, name, code, is_active) VALUES (?, ?, ?, ?, ?)', [orgId, branchId, data.name, data.code || null, data.isActive === false ? 0 : 1]); const [rows] = await this.pool().execute<RowDataPacket[]>('SELECT * FROM inventory_categories WHERE id = ? AND organization_id = ? AND branch_id = ?', [r.insertId, orgId, branchId]); return mapCategory(rows[0]); } catch (e:any) { if (e?.errno === 1062) throw new ConflictError('Inventory category name or code already exists', 'INVENTORY_CATEGORY_DUPLICATE'); throw e; } }
  async updateCategory(orgId: number, branchId: number, id: number, data: any) { const [rows] = await this.pool().execute<RowDataPacket[]>('SELECT * FROM inventory_categories WHERE id = ? AND organization_id = ? AND branch_id = ? FOR UPDATE', [id, orgId, branchId]); if (!rows.length) throw new NotFoundError('Inventory category not found', 'INVENTORY_CATEGORY_NOT_FOUND'); const r=rows[0]; try { await this.pool().execute('UPDATE inventory_categories SET name=?, code=?, is_active=?, updated_at=NOW() WHERE id=? AND organization_id=? AND branch_id=?', [data.name ?? r.name, data.code !== undefined ? data.code : r.code, data.isActive === undefined ? r.is_active : data.isActive ? 1 : 0, id, orgId, branchId]); const [u]=await this.pool().execute<RowDataPacket[]>('SELECT * FROM inventory_categories WHERE id = ?', [id]); return mapCategory(u[0]); } catch(e:any){ if(e?.errno===1062) throw new ConflictError('Inventory category name or code already exists','INVENTORY_CATEGORY_DUPLICATE'); throw e; } }

  async listLocations(orgId: number, branchId: number) { await this.assertBranch(orgId, branchId); const [rows]=await this.pool().execute<RowDataPacket[]>('SELECT * FROM inventory_locations WHERE organization_id=? AND branch_id=? ORDER BY is_active DESC, name',[orgId,branchId]); return rows.map(mapLocation); }
  async createLocation(orgId: number, branchId: number, data: any) { await this.assertBranch(orgId, branchId); try { const [r]=await this.pool().execute<ResultSetHeader>('INSERT INTO inventory_locations (organization_id, branch_id, name, code, is_active, notes) VALUES (?, ?, ?, ?, ?, ?)',[orgId,branchId,data.name,data.code.toUpperCase(),data.isActive===false?0:1,data.notes??null]); const [rows]=await this.pool().execute<RowDataPacket[]>('SELECT * FROM inventory_locations WHERE id=? AND organization_id=? AND branch_id=?',[r.insertId,orgId,branchId]); return mapLocation(rows[0]); } catch(e:any){ if(e?.errno===1062) throw new ConflictError('Inventory location name or code already exists','INVENTORY_LOCATION_DUPLICATE'); throw e; } }
  async updateLocation(orgId:number,branchId:number,id:number,data:any){ const [rows]=await this.pool().execute<RowDataPacket[]>('SELECT * FROM inventory_locations WHERE id=? AND organization_id=? AND branch_id=? FOR UPDATE',[id,orgId,branchId]); if(!rows.length) throw new NotFoundError('Inventory location not found','INVENTORY_LOCATION_NOT_FOUND'); const r=rows[0]; const [active] = await this.pool().execute<RowDataPacket[]>('SELECT COUNT(*) c FROM inventory_balances WHERE organization_id=? AND branch_id=? AND location_id=?',[orgId,branchId,id]); if(data.isActive===false && Number(active[0].c)>0){ /* historical balances remain readable */ } try { await this.pool().execute('UPDATE inventory_locations SET name=?, code=?, is_active=?, notes=?, updated_at=NOW() WHERE id=? AND organization_id=? AND branch_id=?',[data.name??r.name,(data.code??r.code).toUpperCase(),data.isActive===undefined?r.is_active:data.isActive?1:0,data.notes!==undefined?data.notes:r.notes,id,orgId,branchId]); const [u]=await this.pool().execute<RowDataPacket[]>('SELECT * FROM inventory_locations WHERE id=?',[id]); return mapLocation(u[0]); } catch(e:any){ if(e?.errno===1062) throw new ConflictError('Inventory location name or code already exists','INVENTORY_LOCATION_DUPLICATE'); throw e; } }

  async validateItem(conn: PoolConnection, orgId: number, branchId: number, itemId: number, forUpdate=false) {
    const [rows]=await conn.execute<RowDataPacket[]>(`SELECT ii.*, u.symbol AS unit_symbol FROM inventory_items ii JOIN units_of_measure u ON u.id=ii.unit_id WHERE ii.id=? AND ii.organization_id=? AND ii.branch_id=? ${forUpdate?'FOR UPDATE':''}`,[itemId,orgId,branchId]);
    if(!rows.length) throw new NotFoundError('Inventory item not found','INVENTORY_ITEM_NOT_FOUND');
    if(!rows[0].is_active) throw new ConflictError('Inventory item is inactive','INVENTORY_ITEM_INACTIVE');
    return rows[0];
  }
  async validateLocation(conn: PoolConnection, orgId:number, branchId:number, locationId:number, forUpdate=false){ const [rows]=await conn.execute<RowDataPacket[]>(`SELECT * FROM inventory_locations WHERE id=? AND organization_id=? AND branch_id=? ${forUpdate?'FOR UPDATE':''}`,[locationId,orgId,branchId]); if(!rows.length) throw new NotFoundError('Inventory location not found','INVENTORY_LOCATION_NOT_FOUND'); if(!rows[0].is_active) throw new ConflictError('Inventory location is inactive','INVENTORY_LOCATION_INACTIVE'); return rows[0]; }

  async listItems(orgId:number,branchId:number,filter:any){
    const clauses=['ii.organization_id=?','ii.branch_id=?']; const params:any[]=[orgId,branchId];
    if(filter.search){ clauses.push('(ii.name LIKE ? OR ii.sku LIKE ?)'); const s=`%${filter.search}%`; params.push(s,s); }
    if(filter.categoryId){clauses.push('ii.category_id=?');params.push(filter.categoryId);}
    if(filter.activeOnly!==false){clauses.push('ii.is_active=TRUE');}
    const [rows]=await this.pool().execute<RowDataPacket[]>(`SELECT ii.*, c.name category_name, u.symbol unit_symbol FROM inventory_items ii LEFT JOIN inventory_categories c ON c.id=ii.category_id AND c.organization_id=ii.organization_id AND c.branch_id=ii.branch_id JOIN units_of_measure u ON u.id=ii.unit_id WHERE ${clauses.join(' AND ')} ORDER BY ii.is_active DESC, ii.name`,params);
    let items=rows.map(mapItem);
    if(filter.locationId||filter.status){ const balances=await this.listStock(orgId,branchId,{locationId:filter.locationId}); const byItem=new Map<number,InventoryBalance[]>(); balances.forEach(b=>{const a=byItem.get(b.inventoryItemId)||[];a.push(b);byItem.set(b.inventoryItemId,a);}); items=items.filter(i=>{const bs=byItem.get(i.id)||[]; const okLoc=!filter.locationId || bs.length>0; if(!filter.status) return okLoc; return okLoc && bs.some(b=>b.status===filter.status);}); }
    return items;
  }
  async getItem(orgId:number,branchId:number,id:number){ const [rows]=await this.pool().execute<RowDataPacket[]>('SELECT ii.*, c.name category_name, u.symbol unit_symbol FROM inventory_items ii LEFT JOIN inventory_categories c ON c.id=ii.category_id AND c.organization_id=ii.organization_id AND c.branch_id=ii.branch_id JOIN units_of_measure u ON u.id=ii.unit_id WHERE ii.id=? AND ii.organization_id=? AND ii.branch_id=?',[id,orgId,branchId]); return rows.length?mapItem(rows[0]):null; }
  async createItem(orgId:number,branchId:number,data:any){ const conn=await this.pool().getConnection(); try{await conn.beginTransaction(); await this.assertBranch(orgId,branchId,conn); await this.validateUnit(conn,orgId,Number(data.unitId)); if(data.categoryId!=null){const [c]=await conn.execute<RowDataPacket[]>('SELECT id FROM inventory_categories WHERE id=? AND organization_id=? AND branch_id=?',[data.categoryId,orgId,branchId]); if(!c.length) throw new BadRequestError('Inventory category does not belong to this branch','INVALID_INVENTORY_CATEGORY');} const [r]=await conn.execute<ResultSetHeader>('INSERT INTO inventory_items (organization_id,branch_id,category_id,unit_id,name,sku,cost_per_unit,reorder_point,reorder_quantity,is_active,notes) VALUES (?,?,?,?,?,?,?,?,?,?,?)',[orgId,branchId,data.categoryId??null,data.unitId,data.name,data.sku||null,q(data.costPerUnit??0),q(data.reorderPoint??0),q(data.reorderQuantity??0),data.isActive===false?0:1,data.notes??null]); const [rows]=await conn.execute<RowDataPacket[]>('SELECT ii.*, c.name category_name, u.symbol unit_symbol FROM inventory_items ii LEFT JOIN inventory_categories c ON c.id=ii.category_id AND c.organization_id=ii.organization_id AND c.branch_id=ii.branch_id JOIN units_of_measure u ON u.id=ii.unit_id WHERE ii.id=?',[r.insertId]); await conn.commit(); return mapItem(rows[0]); }catch(e:any){await conn.rollback();if(e?.errno===1062)throw new ConflictError('Inventory item SKU already exists in this branch','INVENTORY_ITEM_DUPLICATE');throw e;}finally{conn.release();} }
  async updateItem(orgId:number,branchId:number,id:number,data:any){ const conn=await this.pool().getConnection(); try{await conn.beginTransaction(); const existing=await this.validateItem(conn,orgId,branchId,id,true); if(data.unitId!==undefined) { await this.validateUnit(conn,orgId,Number(data.unitId)); if(Number(data.unitId)!==Number(existing.unit_id)){ const [movementRows]=await conn.execute<RowDataPacket[]>('SELECT id FROM inventory_movements WHERE organization_id=? AND branch_id=? AND inventory_item_id=? LIMIT 1',[orgId,branchId,id]); if(movementRows.length) throw new ConflictError('Unit of measure cannot change after stock movements exist','INVENTORY_UNIT_IMMUTABLE'); } } if(data.categoryId!==undefined&&data.categoryId!=null){const [c]=await conn.execute<RowDataPacket[]>('SELECT id FROM inventory_categories WHERE id=? AND organization_id=? AND branch_id=?',[data.categoryId,orgId,branchId]);if(!c.length)throw new BadRequestError('Inventory category does not belong to this branch','INVALID_INVENTORY_CATEGORY');} await conn.execute('UPDATE inventory_items SET category_id=?, unit_id=?, name=?, sku=?, cost_per_unit=?, reorder_point=?, reorder_quantity=?, is_active=?, notes=?, updated_at=NOW() WHERE id=? AND organization_id=? AND branch_id=?',[data.categoryId!==undefined?data.categoryId:existing.category_id,data.unitId??existing.unit_id,data.name??existing.name,data.sku!==undefined?data.sku:existing.sku,q(data.costPerUnit??existing.cost_per_unit),q(data.reorderPoint??existing.reorder_point),q(data.reorderQuantity??existing.reorder_quantity),data.isActive===undefined?existing.is_active:data.isActive?1:0,data.notes!==undefined?data.notes:existing.notes,id,orgId,branchId]);const [rows]=await conn.execute<RowDataPacket[]>('SELECT ii.*, c.name category_name, u.symbol unit_symbol FROM inventory_items ii LEFT JOIN inventory_categories c ON c.id=ii.category_id AND c.organization_id=ii.organization_id AND c.branch_id=ii.branch_id JOIN units_of_measure u ON u.id=ii.unit_id WHERE ii.id=?',[id]); await conn.commit(); return mapItem(rows[0]);}catch(e:any){await conn.rollback();if(e?.errno===1062)throw new ConflictError('Inventory item SKU already exists in this branch','INVENTORY_ITEM_DUPLICATE');throw e;}finally{conn.release();} }

  async balance(orgId:number,branchId:number,itemId:number,locationId:number,conn:PoolConnection){ const [rows]=await conn.execute<RowDataPacket[]>('SELECT ib.*, ii.name item_name, ii.sku, ii.reorder_point, ii.reorder_quantity, ii.unit_id, u.symbol unit_symbol, c.name category_name, il.name location_name FROM inventory_balances ib JOIN inventory_items ii ON ii.id=ib.inventory_item_id JOIN units_of_measure u ON u.id=ii.unit_id LEFT JOIN inventory_categories c ON c.id=ii.category_id JOIN inventory_locations il ON il.id=ib.location_id WHERE ib.organization_id=? AND ib.branch_id=? AND ib.inventory_item_id=? AND ib.location_id=? FOR UPDATE',[orgId,branchId,itemId,locationId]); return rows.length?rows[0]:null; }
  async ensureBalance(conn:PoolConnection,orgId:number,branchId:number,itemId:number,locationId:number){ await conn.execute('INSERT IGNORE INTO inventory_balances (organization_id,branch_id,inventory_item_id,location_id,current_quantity) VALUES (?,?,?,?,0)',[orgId,branchId,itemId,locationId]); return this.balance(orgId,branchId,itemId,locationId,conn); }

  async updateWeightedAverageCost(orgId:number,branchId:number,itemId:number,incomingQuantity:number,incomingUnitCost:number,conn:PoolConnection){
    if(incomingQuantity<=0) return;
    if(incomingUnitCost<0 || !Number.isFinite(incomingUnitCost)) throw new BadRequestError('Incoming acquisition cost must be non-negative','INVALID_ACQUISITION_COST');
    const item=await this.validateItem(conn,orgId,branchId,itemId,true);
    const [stockRows]=await conn.execute<RowDataPacket[]>('SELECT COALESCE(SUM(current_quantity),0) total_quantity FROM inventory_balances WHERE organization_id=? AND branch_id=? AND inventory_item_id=?',[orgId,branchId,itemId]);
    const currentQuantity=q(Number(stockRows[0]?.total_quantity||0));
    const currentCost=q(Number(item.cost_per_unit||0));
    const newQuantity=q(incomingQuantity);
    const denominator=q(currentQuantity+newQuantity);
    const weighted=denominator>0?q(((currentQuantity*currentCost)+(newQuantity*q(incomingUnitCost)))/denominator):q(incomingUnitCost);
    await conn.execute('UPDATE inventory_items SET cost_per_unit=?,updated_at=NOW() WHERE id=? AND organization_id=? AND branch_id=?',[weighted,itemId,orgId,branchId]);
    return weighted;
  }

  async mutateStock(orgId:number,branchId:number,itemId:number,locationId:number,delta:number,movementType:InventoryMovementType,reason:string,performedBy:number,referenceType:string|null,referenceId:number|null,conn:PoolConnection){
    const item=await this.validateItem(conn,orgId,branchId,itemId,true); await this.validateLocation(conn,orgId,branchId,locationId,true); const b=await this.ensureBalance(conn,orgId,branchId,itemId,locationId); if(!b) throw new Error('Balance row unavailable'); const before=q(Number(b.current_quantity)); const after=q(before+delta); if(after<0) throw new ConflictError('Insufficient stock','INSUFFICIENT_STOCK'); if(movementType==='OPENING' && b.opening_recorded) throw new ConflictError('Opening stock has already been recorded for this item and location','OPENING_STOCK_ALREADY_RECORDED'); if(movementType==='OPENING' && Number(b.version)>0) throw new ConflictError('Opening stock can only be recorded before other stock movements','OPENING_STOCK_NOT_INITIAL'); await conn.execute('UPDATE inventory_balances SET current_quantity=?, opening_recorded=CASE WHEN ?=\'OPENING\' THEN TRUE ELSE opening_recorded END, version=version+1, updated_at=NOW() WHERE inventory_item_id=? AND location_id=?',[after,movementType,itemId,locationId]); const [r]=await conn.execute<ResultSetHeader>('INSERT INTO inventory_movements (organization_id,branch_id,inventory_item_id,location_id,movement_type,quantity,unit_id,before_quantity,after_quantity,reason,reference_type,reference_id,performed_by) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)',[orgId,branchId,itemId,locationId,movementType,Math.abs(delta),Number(item.unit_id),before,after,reason,referenceType,referenceId,performedBy]); return r.insertId;
  }

  async openingStock(orgId:number,branchId:number,data:any,performedBy:number){const conn=await this.pool().getConnection();try{await conn.beginTransaction();await this.mutateStock(orgId,branchId,data.inventoryItemId,data.locationId,q(data.quantity),'OPENING',data.reason,performedBy,'OPENING_STOCK',null,conn);await conn.commit();return this.getStockForItem(orgId,branchId,data.inventoryItemId);}catch(e){await conn.rollback();throw e;}finally{conn.release();}}
  async adjustment(orgId:number,branchId:number,data:any,performedBy:number){const conn=await this.pool().getConnection();try{await conn.beginTransaction();const delta=q(data.deltaQuantity);const type=delta>0?'ADJUSTMENT_IN':'ADJUSTMENT_OUT';await this.mutateStock(orgId,branchId,data.inventoryItemId,data.locationId,delta,type,data.reason,performedBy,'ADJUSTMENT',null,conn);await conn.commit();return this.getStockForItem(orgId,branchId,data.inventoryItemId);}catch(e){await conn.rollback();throw e;}finally{conn.release();}}
  async transfer(orgId:number,branchId:number,data:any,performedBy:number){
    if(Number(data.fromLocationId)===Number(data.toLocationId)) throw new BadRequestError('Source and destination locations must be different','SAME_INVENTORY_LOCATION');
    const conn=await this.pool().getConnection();
    try{
      await conn.beginTransaction();
      const locationIds=[Number(data.fromLocationId),Number(data.toLocationId)].sort((a,b)=>a-b);
      await this.validateLocation(conn,orgId,branchId,locationIds[0],true);
      await this.validateLocation(conn,orgId,branchId,locationIds[1],true);
      await this.validateItem(conn,orgId,branchId,data.inventoryItemId,true);
      // Lock both balance rows in deterministic location order before applying either side.
      await this.ensureBalance(conn,orgId,branchId,data.inventoryItemId,locationIds[0]);
      await this.ensureBalance(conn,orgId,branchId,data.inventoryItemId,locationIds[1]);
      await this.mutateStock(orgId,branchId,data.inventoryItemId,data.fromLocationId,-q(data.quantity),'TRANSFER_OUT',data.reason,performedBy,'INVENTORY_TRANSFER',null,conn);
      await this.mutateStock(orgId,branchId,data.inventoryItemId,data.toLocationId,q(data.quantity),'TRANSFER_IN',data.reason,performedBy,'INVENTORY_TRANSFER',null,conn);
      await conn.commit();
      return this.getStockForItem(orgId,branchId,data.inventoryItemId);
    }catch(e){await conn.rollback();throw e;}finally{conn.release();}
  }

  async listStock(orgId:number,branchId:number,filter:any={}){
    const clauses=['ii.organization_id=?','ii.branch_id=?','ii.is_active=TRUE','il.organization_id=?','il.branch_id=?','il.is_active=TRUE'];
    const params:any[]=[orgId,branchId,orgId,branchId];
    if(filter.itemId){clauses.push('ii.id=?');params.push(filter.itemId);}
    if(filter.locationId){clauses.push('il.id=?');params.push(filter.locationId);}
    const [rows]=await this.pool().execute<RowDataPacket[]>(`
      SELECT ii.id inventory_item_id, il.id location_id, COALESCE(ib.current_quantity,0) current_quantity,
             ii.name item_name, ii.sku, ii.reorder_point, ii.reorder_quantity, ii.unit_id, u.symbol unit_symbol,
             c.name category_name, il.name location_name
      FROM inventory_items ii
      JOIN inventory_locations il ON il.organization_id=ii.organization_id AND il.branch_id=ii.branch_id
      JOIN units_of_measure u ON u.id=ii.unit_id
      LEFT JOIN inventory_categories c ON c.id=ii.category_id AND c.organization_id=ii.organization_id AND c.branch_id=ii.branch_id
      LEFT JOIN inventory_balances ib ON ib.organization_id=ii.organization_id AND ib.branch_id=ii.branch_id AND ib.inventory_item_id=ii.id AND ib.location_id=il.id
      WHERE ${clauses.join(' AND ')} ORDER BY il.name, ii.name`,params);
    return rows.map(r=>({inventoryItemId:Number(r.inventory_item_id),locationId:Number(r.location_id),itemName:String(r.item_name),sku:r.sku==null?null:String(r.sku),categoryName:r.category_name==null?null:String(r.category_name),unitId:Number(r.unit_id),unitSymbol:String(r.unit_symbol),currentQuantity:Number(r.current_quantity),reorderPoint:Number(r.reorder_point),reorderQuantity:Number(r.reorder_quantity),status:stockStatus(Number(r.current_quantity),Number(r.reorder_point)),locationName:String(r.location_name)} as InventoryBalance));
  }
  async getStockForItem(orgId:number,branchId:number,itemId:number){await this.pool().execute('SELECT 1 FROM inventory_items WHERE id=? AND organization_id=? AND branch_id=?',[itemId,orgId,branchId]);return this.listStock(orgId,branchId,{itemId});}

  async movements(orgId:number,branchId:number,filter:any={}){const clauses=['m.organization_id=?','m.branch_id=?'];const params:any[]=[orgId,branchId];if(filter.inventoryItemId){clauses.push('m.inventory_item_id=?');params.push(filter.inventoryItemId);}if(filter.locationId){clauses.push('m.location_id=?');params.push(filter.locationId);}if(filter.movementType){clauses.push('m.movement_type=?');params.push(filter.movementType);}if(filter.performedBy){clauses.push('m.performed_by=?');params.push(filter.performedBy);}if(filter.from){clauses.push('DATE(m.created_at)>=?');params.push(filter.from);}if(filter.to){clauses.push('DATE(m.created_at)<=?');params.push(filter.to);}const [rows]=await this.pool().execute<RowDataPacket[]>(`SELECT m.*, ii.name item_name, il.name location_name, u.symbol unit_symbol FROM inventory_movements m JOIN inventory_items ii ON ii.id=m.inventory_item_id JOIN inventory_locations il ON il.id=m.location_id JOIN units_of_measure u ON u.id=m.unit_id WHERE ${clauses.join(' AND ')} ORDER BY m.created_at DESC, m.id DESC LIMIT 1000`,params);return rows.map(mapMovement);}

  async createCount(orgId:number,branchId:number,locationId:number,itemIds:number[],createdBy:number,notes?:string|null){const conn=await this.pool().getConnection();try{await conn.beginTransaction();await this.validateLocation(conn,orgId,branchId,locationId,true);const unique=[...new Set(itemIds.map(Number))];const [items]=await conn.execute<RowDataPacket[]>(`SELECT ii.id, ii.name, ii.unit_id, u.symbol unit_symbol FROM inventory_items ii JOIN units_of_measure u ON u.id=ii.unit_id WHERE ii.organization_id=? AND ii.branch_id=? AND ii.is_active=TRUE AND ii.id IN (${unique.map(()=>'?').join(',')}) FOR UPDATE`,[orgId,branchId,...unique]);if(items.length!==unique.length)throw new BadRequestError('One or more inventory items are invalid for this branch','INVALID_COUNT_ITEM');const [r]=await conn.execute<ResultSetHeader>('INSERT INTO inventory_counts (organization_id,branch_id,location_id,status,created_by,notes) VALUES (?,?,?,\'DRAFT\',?,?)',[orgId,branchId,locationId,createdBy,notes??null]);for(const item of items){const b=await this.ensureBalance(conn,orgId,branchId,Number(item.id),locationId);await conn.execute('INSERT INTO inventory_count_items (count_id,organization_id,branch_id,inventory_item_id,system_quantity,counted_quantity,variance_quantity,unit_id) VALUES (?,?,?,?,?,?,?,?)',[r.insertId,orgId,branchId,Number(item.id),Number(b!.current_quantity),Number(b!.current_quantity),0,Number(item.unit_id)]);}await conn.commit();return this.getCount(orgId,branchId,Number(r.insertId));}catch(e){await conn.rollback();throw e;}finally{conn.release();}}
  async getCount(orgId:number,branchId:number,id:number){const [rows]=await this.pool().execute<RowDataPacket[]>(`SELECT ic.*, il.name location_name FROM inventory_counts ic JOIN inventory_locations il ON il.id=ic.location_id WHERE ic.id=? AND ic.organization_id=? AND ic.branch_id=?`,[id,orgId,branchId]);if(!rows.length)return null;const [items]=await this.pool().execute<RowDataPacket[]>(`SELECT ici.*, ii.name item_name, u.symbol unit_symbol FROM inventory_count_items ici JOIN inventory_items ii ON ii.id=ici.inventory_item_id JOIN units_of_measure u ON u.id=ici.unit_id WHERE ici.count_id=? AND ici.organization_id=? AND ici.branch_id=? ORDER BY ii.name`,[id,orgId,branchId]);return {id:Number(rows[0].id),organizationId:Number(rows[0].organization_id),branchId:Number(rows[0].branch_id),locationId:Number(rows[0].location_id),locationName:String(rows[0].location_name),status:rows[0].status,createdBy:Number(rows[0].created_by),confirmedBy:rows[0].confirmed_by==null?null:Number(rows[0].confirmed_by),createdAt:iso(rows[0].created_at),confirmedAt:rows[0].confirmed_at?iso(rows[0].confirmed_at):null,notes:rows[0].notes??null,items:items.map(i=>({id:Number(i.id),inventoryItemId:Number(i.inventory_item_id),itemName:String(i.item_name),unitSymbol:String(i.unit_symbol),systemQuantity:Number(i.system_quantity),countedQuantity:Number(i.counted_quantity),varianceQuantity:Number(i.variance_quantity)}))} as InventoryCount;}
  async listCounts(orgId:number,branchId:number){const [rows]=await this.pool().execute<RowDataPacket[]>(`SELECT ic.*, il.name location_name FROM inventory_counts ic JOIN inventory_locations il ON il.id=ic.location_id WHERE ic.organization_id=? AND ic.branch_id=? ORDER BY ic.created_at DESC LIMIT 200`,[orgId,branchId]);return rows.map(r=>({id:Number(r.id),organizationId:Number(r.organization_id),branchId:Number(r.branch_id),locationId:Number(r.location_id),locationName:String(r.location_name),status:r.status,createdBy:Number(r.created_by),confirmedBy:r.confirmed_by==null?null:Number(r.confirmed_by),createdAt:iso(r.created_at),confirmedAt:r.confirmed_at?iso(r.confirmed_at):null,notes:r.notes??null,items:[]}));}
  async confirmCount(orgId:number,branchId:number,id:number,performedBy:number,inputItems:any[]){const conn=await this.pool().getConnection();try{await conn.beginTransaction();const [countRows]=await conn.execute<RowDataPacket[]>('SELECT * FROM inventory_counts WHERE id=? AND organization_id=? AND branch_id=? FOR UPDATE',[id,orgId,branchId]);if(!countRows.length)throw new NotFoundError('Stock count not found','INVENTORY_COUNT_NOT_FOUND');if(countRows[0].status!=='DRAFT')throw new ConflictError('Only draft stock counts can be confirmed','INVENTORY_COUNT_NOT_DRAFT');const [countItems]=await conn.execute<RowDataPacket[]>('SELECT ici.*, ii.name, ii.unit_id FROM inventory_count_items ici JOIN inventory_items ii ON ii.id=ici.inventory_item_id WHERE ici.count_id=? AND ici.organization_id=? AND ici.branch_id=? FOR UPDATE',[id,orgId,branchId]);const submitted=new Map<number,number>();for(const row of inputItems){if(submitted.has(Number(row.inventoryItemId)))throw new BadRequestError('Duplicate item in stock count','DUPLICATE_COUNT_ITEM');submitted.set(Number(row.inventoryItemId),q(row.countedQuantity));}if(submitted.size!==countItems.length || countItems.some(i=>!submitted.has(Number(i.inventory_item_id))))throw new BadRequestError('Stock count must include every item in the count','INCOMPLETE_STOCK_COUNT');for(const ci of countItems){const itemId=Number(ci.inventory_item_id);const b=await this.balance(orgId,branchId,itemId,Number(countRows[0].location_id),conn);if(!b)throw new ConflictError('Stock balance is missing','STOCK_BALANCE_MISSING');const current=q(Number(b.current_quantity));const recorded=q(Number(ci.system_quantity));if(current!==recorded)throw new ConflictError('Stock changed since this count was started; refresh and recount','STALE_STOCK_COUNT');const counted=submitted.get(itemId)!;const variance=q(counted-recorded);await conn.execute('UPDATE inventory_count_items SET counted_quantity=?, variance_quantity=? WHERE id=?',[counted,variance,Number(ci.id)]);if(variance!==0)await this.mutateStock(orgId,branchId,itemId,Number(countRows[0].location_id),variance,'COUNT_CORRECTION','Physical stock count',performedBy,'INVENTORY_COUNT',id,conn);}await conn.execute('UPDATE inventory_counts SET status=\'CONFIRMED\', confirmed_by=?, confirmed_at=NOW() WHERE id=?',[performedBy,id]);await conn.commit();return this.getCount(orgId,branchId,id);}catch(e){await conn.rollback();throw e;}finally{conn.release();}}

  async overview(orgId:number,branchId:number):Promise<InventoryOverview>{const stock=await this.listStock(orgId,branchId);const [items]=await this.pool().execute<RowDataPacket[]>('SELECT COUNT(*) c FROM inventory_items WHERE organization_id=? AND branch_id=? AND is_active=TRUE',[orgId,branchId]);const [locs]=await this.pool().execute<RowDataPacket[]>('SELECT COUNT(*) c FROM inventory_locations WHERE organization_id=? AND branch_id=? AND is_active=TRUE',[orgId,branchId]);const low=new Set(stock.filter(s=>s.status==='LOW_STOCK').map(s=>s.inventoryItemId));const out=new Set(stock.filter(s=>s.status==='OUT_OF_STOCK').map(s=>s.inventoryItemId));return {totalItems:Number(items[0].c),lowStockItems:low.size,outOfStockItems:out.size,activeLocations:Number(locs[0].c),recentMovements:(await this.movements(orgId,branchId)).slice(0,20)};}
}

export const inventoryRepository = new InventoryRepository();
