import { migrationRunner } from './runner';
import { migration001Phase2IdentityAndTenancy } from './001_phase2_identity_and_tenancy';
import { migration002Phase3AdministrationAndMasterData } from './002_phase3_administration_and_master_data';
import { migration003MenuCategories } from './003_menu_categories';
import { migration004MenuItems } from './004_menu_items';
import { migration005TableAllocations } from './005_table_allocations';
import { migration006OrderDomain } from './006_order_domain';
import { migration007RbacRoleConsolidation } from './007_rbac_role_consolidation';
import { migration008Phase3KotOperations } from './008_phase3_kot_operations';
import { migration009OwnerBootstrap } from './009_phase3_5_owner_bootstrap';
import { migration010FinancialFoundation } from './010_financial_foundation';
import { migration011ServiceLifecycle } from './011_service_lifecycle';
import { migration012ModifiersVariantsSnapshots } from './012_modifiers_variants_snapshots';
import { migration013TableOrderOperations } from './013_table_order_operations';
import { migration014BillSplitting } from './014_bill_splitting';
import { migration015ManagementFoundation } from './015_management_foundation';
import { migration016ShiftBusinessDay } from './016_shift_business_day';
import { migration017InventoryFoundation } from './017_inventory_foundation';
import { migration018Purchasing } from './018_purchasing';
import { migration019PurchasingInventoryBridge } from './019_purchasing_inventory_bridge';
import { migration020RecipesFoodCosting } from './020_recipes_food_costing';
import { migration021ExpenseManagement } from './021_expense_management';
import { migration022ReportsAndDashboard } from './022_reports_and_dashboard';
import { migration023AlertsOperationalNotifications } from './023_alerts_operational_notifications';
import { migration024SecurityConcurrencyOfflineHardening } from './024_security_concurrency_offline_hardening';
import { migration025MembershipTransactionIntegration } from './025_membership_transaction_integration';
import { migration026BillSplitRequests } from './026_bill_split_requests';
import { migration027ActivityAuditLog } from './027_activity_audit_log';
import { migration028AccountRecoveryAndPhone } from './028_account_recovery_and_phone';
import { migration029BranchWideStaffAccess } from './029_branch_wide_staff_access';
import { migration030OperationalPerformanceLifecycle } from './030_operational_performance_lifecycle';
import { migration031ReceiptPrintingSettings } from './031_receipt_printing_settings';
import { migration032ComplimentaryItems } from './032_complimentary_items';
import { migration033ReconcileServedKots } from './033_reconcile_served_kots';
import { migration034DineInAppendIdempotency } from './034_dine_in_append_idempotency';
import { migration035OperationalRolePermissionCleanup } from './035_operational_role_permission_cleanup';
import { migration036DedupeSystemRoles } from './036_dedupe_system_roles';
import { migration037PartialServiceItems } from './037_partial_service_items';
import { migration038ReconcileTableOccupancy } from './038_reconcile_table_occupancy';
import { migration039PermissionMatrixHardening } from './039_permission_matrix_hardening';
import { migration040FinancialInvariants } from './040_financial_invariants';
import { migration041DomainAuditEvents } from './041_domain_audit_events';
import { migration042ShiftBusinessDayInvariants } from './042_shift_business_day_invariants';
import { migration043RestaurantCodeAuth } from './043_restaurant_code_auth';
import { migration044RestaurantHandleAuth } from './044_restaurant_handle_auth';
import { migration045MixedSettlementCredit } from './045_mixed_settlement_credit';
import { migration046ReceiptPrintCopies } from './046_receipt_print_copies';
import { migration047MultiTableDining } from './047_multi_table_dining';
import { migration048ActionCenterRules } from './048_action_center_rules';
import { migration049SimpleStockInventory } from './049_simple_stock_inventory';
import { migration050TakeawayPickupLifecycle } from './050_takeaway_pickup_lifecycle';
import { migration051OrderRounds } from './051_order_rounds';
import { migration052MenuComboComponents } from './052_menu_combo_components';
import { migration053CustomerCreditStatement } from './053_customer_credit_statement';
import { migration054PlatformAdminIdentity } from './054_platform_admin_identity';
import { migration055OrganizationEntitlementFoundation } from './055_organization_entitlement_foundation';
import { migration056OwnerAccessStatusSessions } from './056_owner_access_status_sessions';
import { migration057PlatformAuditLogs } from './057_platform_audit_logs';
import { migration058ScheduledSuspensionMetadata } from './058_scheduled_suspension_metadata';
import { migration059LifecycleAutomationAttention } from './059_lifecycle_automation_attention';
import { migration060OrganizationActivationRequests } from './060_organization_activation_requests';
import { migration061BranchCoordinates } from './061_branch_coordinates';
import { migration062PlatformBusinessMetricsIndex } from './062_platform_business_metrics_index';
import { migration063PlatformAdminCredentials } from './063_platform_admin_credentials';
import { migration064PlatformAdminPasswordDefault } from './064_platform_admin_password_default';

export * from './types';
export * from './runner';
export * from './001_phase2_identity_and_tenancy';
export * from './002_phase3_administration_and_master_data';
export * from './003_menu_categories';
export * from './004_menu_items';
export * from './005_table_allocations';
export * from './006_order_domain';
export * from './007_rbac_role_consolidation';
export * from './008_phase3_kot_operations';
export * from './009_phase3_5_owner_bootstrap';
export * from './010_financial_foundation';
export * from './011_service_lifecycle';
export * from './012_modifiers_variants_snapshots';
export * from './013_table_order_operations';
export * from './014_bill_splitting';
export * from './015_management_foundation';
export * from './016_shift_business_day';
export * from './017_inventory_foundation';
export * from './018_purchasing';
export * from './019_purchasing_inventory_bridge';
export * from './020_recipes_food_costing';
export * from './021_expense_management';
export * from './022_reports_and_dashboard';
export * from './023_alerts_operational_notifications';
export * from './024_security_concurrency_offline_hardening';
export * from './025_membership_transaction_integration';
export * from './026_bill_split_requests';
export * from './027_activity_audit_log';
export * from './028_account_recovery_and_phone';
export * from './029_branch_wide_staff_access';
export * from './030_operational_performance_lifecycle';
export * from './031_receipt_printing_settings';
export * from './032_complimentary_items';
export * from './033_reconcile_served_kots';
export * from './034_dine_in_append_idempotency';
export * from './035_operational_role_permission_cleanup';
export * from './036_dedupe_system_roles';
export * from './037_partial_service_items';
export * from './038_reconcile_table_occupancy';
export * from './039_permission_matrix_hardening';
export * from './040_financial_invariants';
export * from './041_domain_audit_events';
export * from './042_shift_business_day_invariants';
export * from './043_restaurant_code_auth';
export * from './044_restaurant_handle_auth';
export * from './045_mixed_settlement_credit';
export * from './046_receipt_print_copies';
export * from './047_multi_table_dining';
export * from './048_action_center_rules';
export * from './049_simple_stock_inventory';
export * from './050_takeaway_pickup_lifecycle';
export * from './051_order_rounds';
export * from './052_menu_combo_components';
export * from './053_customer_credit_statement';
export * from './054_platform_admin_identity';
export * from './055_organization_entitlement_foundation';
export * from './056_owner_access_status_sessions';
export * from './057_platform_audit_logs';
export * from './058_scheduled_suspension_metadata';
export * from './059_lifecycle_automation_attention';
export * from './060_organization_activation_requests';
export * from './061_branch_coordinates';
export * from './062_platform_business_metrics_index';
export * from './063_platform_admin_credentials';
export * from './064_platform_admin_password_default';

try {
  migrationRunner.registerMigration(migration001Phase2IdentityAndTenancy);
  migrationRunner.registerMigration(migration002Phase3AdministrationAndMasterData);
  migrationRunner.registerMigration(migration003MenuCategories);
  migrationRunner.registerMigration(migration004MenuItems);
  migrationRunner.registerMigration(migration005TableAllocations);
  migrationRunner.registerMigration(migration006OrderDomain);
  migrationRunner.registerMigration(migration007RbacRoleConsolidation);
  migrationRunner.registerMigration(migration008Phase3KotOperations);
  migrationRunner.registerMigration(migration009OwnerBootstrap);
  migrationRunner.registerMigration(migration010FinancialFoundation);
  migrationRunner.registerMigration(migration011ServiceLifecycle);
  migrationRunner.registerMigration(migration012ModifiersVariantsSnapshots);
  migrationRunner.registerMigration(migration013TableOrderOperations);
  migrationRunner.registerMigration(migration014BillSplitting);
  migrationRunner.registerMigration(migration015ManagementFoundation);
  migrationRunner.registerMigration(migration016ShiftBusinessDay);
  migrationRunner.registerMigration(migration017InventoryFoundation);
  migrationRunner.registerMigration(migration018Purchasing);
  migrationRunner.registerMigration(migration019PurchasingInventoryBridge);
  migrationRunner.registerMigration(migration020RecipesFoodCosting);
  migrationRunner.registerMigration(migration021ExpenseManagement);
  migrationRunner.registerMigration(migration022ReportsAndDashboard);
  migrationRunner.registerMigration(migration023AlertsOperationalNotifications);
  migrationRunner.registerMigration(migration024SecurityConcurrencyOfflineHardening);
  migrationRunner.registerMigration(migration025MembershipTransactionIntegration);
  migrationRunner.registerMigration(migration026BillSplitRequests);
  migrationRunner.registerMigration(migration027ActivityAuditLog);
  migrationRunner.registerMigration(migration028AccountRecoveryAndPhone);
  migrationRunner.registerMigration(migration029BranchWideStaffAccess);
  migrationRunner.registerMigration(migration030OperationalPerformanceLifecycle);
  migrationRunner.registerMigration(migration031ReceiptPrintingSettings);
  migrationRunner.registerMigration(migration032ComplimentaryItems);
  migrationRunner.registerMigration(migration033ReconcileServedKots);
  migrationRunner.registerMigration(migration034DineInAppendIdempotency);
  migrationRunner.registerMigration(migration035OperationalRolePermissionCleanup);
  migrationRunner.registerMigration(migration036DedupeSystemRoles);
  migrationRunner.registerMigration(migration037PartialServiceItems);
  migrationRunner.registerMigration(migration038ReconcileTableOccupancy);
  migrationRunner.registerMigration(migration039PermissionMatrixHardening);
  migrationRunner.registerMigration(migration040FinancialInvariants);
  migrationRunner.registerMigration(migration041DomainAuditEvents);
  migrationRunner.registerMigration(migration042ShiftBusinessDayInvariants);
  migrationRunner.registerMigration(migration043RestaurantCodeAuth);
  migrationRunner.registerMigration(migration044RestaurantHandleAuth);
  migrationRunner.registerMigration(migration045MixedSettlementCredit);
  migrationRunner.registerMigration(migration046ReceiptPrintCopies);
  migrationRunner.registerMigration(migration047MultiTableDining);
  migrationRunner.registerMigration(migration048ActionCenterRules);
  migrationRunner.registerMigration(migration049SimpleStockInventory);
  migrationRunner.registerMigration(migration050TakeawayPickupLifecycle);
  migrationRunner.registerMigration(migration051OrderRounds);
  migrationRunner.registerMigration(migration052MenuComboComponents);
  migrationRunner.registerMigration(migration053CustomerCreditStatement);
  migrationRunner.registerMigration(migration054PlatformAdminIdentity);
  migrationRunner.registerMigration(migration055OrganizationEntitlementFoundation);
  migrationRunner.registerMigration(migration056OwnerAccessStatusSessions);
  migrationRunner.registerMigration(migration057PlatformAuditLogs);
  migrationRunner.registerMigration(migration058ScheduledSuspensionMetadata);
  migrationRunner.registerMigration(migration059LifecycleAutomationAttention);
  migrationRunner.registerMigration(migration060OrganizationActivationRequests);
  migrationRunner.registerMigration(migration061BranchCoordinates);
  migrationRunner.registerMigration(migration062PlatformBusinessMetricsIndex);
  migrationRunner.registerMigration(migration063PlatformAdminCredentials);
  migrationRunner.registerMigration(migration064PlatformAdminPasswordDefault);
} catch {
  // Already registered or initialized
}
