import { Request,Response,NextFunction } from 'express';
import { ApiSuccessResponse } from '../../shared/types';
import { BadRequestError,ForbiddenError } from '../../shared/errors';
import { expenseRepository } from './repository';
import { realtimePublisher } from '../../realtime/publisher';
function ctx(req:Request){if(!req.user?.organizationId)throw new ForbiddenError('Authenticated tenant context is missing','MISSING_TENANT_CONTEXT');if(!req.user.activeBranchId)throw new ForbiddenError('Active branch context is missing','MISSING_BRANCH_CONTEXT');return{organizationId:req.user.organizationId,branchId:req.user.activeBranchId,userId:req.user.id};}
function id(v:unknown,label:string){const n=Number(v);if(!Number.isInteger(n)||n<=0)throw new BadRequestError(`Valid ${label} ID is required`,`INVALID_${label.toUpperCase()}_ID`);return n;}
export class ExpenseController{
  listCategories=async(req:Request,res:Response,next:NextFunction)=>{try{const c=ctx(req);res.json({success:true,data:await expenseRepository.listCategories(c.organizationId)} satisfies ApiSuccessResponse);}catch(e){next(e);}};
  createCategory=async(req:Request,res:Response,next:NextFunction)=>{try{const c=ctx(req);const data=await expenseRepository.createCategory(c.organizationId,c.userId,req.body);realtimePublisher.publish({type:'expense.category.updated',organizationId:c.organizationId,branchId:c.branchId,entityType:'expense_category',entityId:data.id,data:{action:'created'}});res.status(201).json({success:true,data} satisfies ApiSuccessResponse);}catch(e){next(e);}};
  updateCategory=async(req:Request,res:Response,next:NextFunction)=>{try{const c=ctx(req);const categoryId=id(req.params.id,'category');const data=await expenseRepository.updateCategory(c.organizationId,categoryId,req.body);realtimePublisher.publish({type:'expense.category.updated',organizationId:c.organizationId,branchId:c.branchId,entityType:'expense_category',entityId:categoryId,data:{action:'updated'}});res.json({success:true,data} satisfies ApiSuccessResponse);}catch(e){next(e);}};
  list=async(req:Request,res:Response,next:NextFunction)=>{try{const c=ctx(req);res.json({success:true,data:await expenseRepository.list(c.organizationId,c.branchId,req.query)} satisfies ApiSuccessResponse);}catch(e){next(e);}};
  get=async(req:Request,res:Response,next:NextFunction)=>{try{const c=ctx(req);res.json({success:true,data:await expenseRepository.get(c.organizationId,c.branchId,id(req.params.id,'expense'))} satisfies ApiSuccessResponse);}catch(e){next(e);}};
  summary=async(req:Request,res:Response,next:NextFunction)=>{try{const c=ctx(req);const businessDayId=req.query.businessDayId?Number(req.query.businessDayId):undefined;res.json({success:true,data:await expenseRepository.summary(c.organizationId,c.branchId,businessDayId)} satisfies ApiSuccessResponse);}catch(e){next(e);}};
  create=async(req:Request,res:Response,next:NextFunction)=>{try{const c=ctx(req);const data=await expenseRepository.create(c.organizationId,c.branchId,c.userId,req.body);realtimePublisher.publish({type:'expense.created',organizationId:c.organizationId,branchId:c.branchId,entityType:'expense',entityId:data.id,data:{status:data.status,amount:data.amount}});res.status(201).json({success:true,data} satisfies ApiSuccessResponse);}catch(e){next(e);}};
  update=async(req:Request,res:Response,next:NextFunction)=>{try{const c=ctx(req);const data=await expenseRepository.update(c.organizationId,c.branchId,id(req.params.id,'expense'),req.body);res.json({success:true,data} satisfies ApiSuccessResponse);}catch(e){next(e);}};
  post=async(req:Request,res:Response,next:NextFunction)=>{try{const c=ctx(req);const data=await expenseRepository.post(c.organizationId,c.branchId,id(req.params.id,'expense'),c.userId);realtimePublisher.publish({type:'expense.posted',organizationId:c.organizationId,branchId:c.branchId,entityType:'expense',entityId:data.id,data:{amount:data.amount,paymentMethodType:data.paymentMethodType,businessDayId:data.businessDayId,shiftId:data.shiftId}});if(data.cashMovementId)realtimePublisher.publish({type:'cash_movement.created',organizationId:c.organizationId,branchId:c.branchId,entityType:'cash_movement',entityId:data.cashMovementId,data:{source:'expense',expenseId:data.id,movementType:'CASH_OUT'}});res.json({success:true,data} satisfies ApiSuccessResponse);}catch(e){next(e);}};
  void=async(req:Request,res:Response,next:NextFunction)=>{try{const c=ctx(req);const data=await expenseRepository.void(c.organizationId,c.branchId,id(req.params.id,'expense'),c.userId,req.body.reason);realtimePublisher.publish({type:'expense.voided',organizationId:c.organizationId,branchId:c.branchId,entityType:'expense',entityId:data.id,data:{reason:data.voidReason}});if(data.reversalCashMovementId)realtimePublisher.publish({type:'cash_movement.created',organizationId:c.organizationId,branchId:c.branchId,entityType:'cash_movement',entityId:data.reversalCashMovementId,data:{source:'expense_void',expenseId:data.id,movementType:'CASH_IN'}});res.json({success:true,data} satisfies ApiSuccessResponse);}catch(e){next(e);}};
}
export const expenseController=new ExpenseController();
