import { Request, Response, NextFunction } from 'express';
import { ApiSuccessResponse } from '../../shared/types';
import { BadRequestError, ForbiddenError } from '../../shared/errors';
import { shiftRepository } from './repository';
import { realtimePublisher } from '../../realtime/publisher';

function ctx(req: Request) {
  if (!req.user?.organizationId) throw new ForbiddenError('Authenticated tenant context is missing', 'MISSING_TENANT_CONTEXT');
  if (!req.user.activeBranchId) throw new ForbiddenError('Active branch context is missing', 'MISSING_BRANCH_CONTEXT');
  return { orgId: req.user.organizationId, branchId: req.user.activeBranchId, userId: req.user.id };
}

export class ShiftController {
  currentBusinessDay = async (req: Request, res: Response, next: NextFunction) => { try { const c = ctx(req); res.json({ success: true, data: await shiftRepository.getCurrentBusinessDay(c.orgId, c.branchId) } satisfies ApiSuccessResponse<any>); } catch (e) { next(e); } };
  listBusinessDays = async (req: Request, res: Response, next: NextFunction) => { try { const c=ctx(req); res.json({success:true,data:await shiftRepository.listBusinessDays(c.orgId,c.branchId)} satisfies ApiSuccessResponse<any>); } catch(e){next(e)} };
  getBusinessDay = async (req: Request,res: Response,next: NextFunction)=>{try{const c=ctx(req);const id=Number(req.params.id);if(!Number.isInteger(id))throw new BadRequestError('Valid business day ID is required','INVALID_BUSINESS_DAY_ID');const day=await shiftRepository.getBusinessDay(id,c.orgId,c.branchId);if(!day)throw new BadRequestError('Business day not found','BUSINESS_DAY_NOT_FOUND');res.json({success:true,data:day} satisfies ApiSuccessResponse<any>)}catch(e){next(e)}};
  openBusinessDay = async (req: Request,res: Response,next: NextFunction)=>{try{const c=ctx(req);const day=await shiftRepository.openBusinessDay(c.orgId,c.branchId,c.userId,req.body.notes);realtimePublisher.publish({type:'business_day.opened',organizationId:c.orgId,branchId:c.branchId,entityType:'business_day',entityId:day.id,data:{businessDate:day.businessDate,status:day.status}});res.status(201).json({success:true,data:day} satisfies ApiSuccessResponse<any>)}catch(e){next(e)}};
  closeBusinessDay = async (req: Request,res: Response,next: NextFunction)=>{try{const c=ctx(req);const id=Number(req.params.id);if(!Number.isInteger(id))throw new BadRequestError('Valid business day ID is required','INVALID_BUSINESS_DAY_ID');const day=await shiftRepository.closeBusinessDay(id,c.orgId,c.branchId,c.userId,req.body.notes);realtimePublisher.publish({type:'business_day.closed',organizationId:c.orgId,branchId:c.branchId,entityType:'business_day',entityId:day.id,data:{businessDate:day.businessDate,status:day.status}});res.json({success:true,data:day} satisfies ApiSuccessResponse<any>)}catch(e){next(e)}};

  listRegisters = async (req: Request,res: Response,next: NextFunction)=>{try{const c=ctx(req);res.json({success:true,data:await shiftRepository.listRegisters(c.orgId,c.branchId)} satisfies ApiSuccessResponse<any>)}catch(e){next(e)}};
  createRegister = async (req: Request,res: Response,next: NextFunction)=>{try{const c=ctx(req);const register=await shiftRepository.createRegister(c.orgId,c.branchId,req.body.name,req.body.code);realtimePublisher.publish({type:'shift.updated',organizationId:c.orgId,branchId:c.branchId,entityType:'shift',entityId:register.id,data:{registerId:register.id,name:register.name,status:'REGISTER_CREATED'}});res.status(201).json({success:true,data:register} satisfies ApiSuccessResponse<any>)}catch(e){next(e)}};
  updateRegister = async (req: Request,res: Response,next: NextFunction)=>{try{const c=ctx(req);const id=Number(req.params.id);if(!Number.isInteger(id))throw new BadRequestError('Valid register ID is required','INVALID_REGISTER_ID');const register=await shiftRepository.updateRegister(c.orgId,c.branchId,id,req.body);realtimePublisher.publish({type:'shift.updated',organizationId:c.orgId,branchId:c.branchId,entityType:'shift',entityId:id,data:{registerId:id,name:register.name,isActive:register.isActive,status:'REGISTER_UPDATED'}});res.json({success:true,data:register} satisfies ApiSuccessResponse<any>)}catch(e){next(e)}};

  currentShift = async (req: Request,res: Response,next: NextFunction)=>{try{const c=ctx(req);res.json({success:true,data:{businessDay:await shiftRepository.getCurrentBusinessDay(c.orgId,c.branchId),shift:await shiftRepository.currentShiftForUser(c.orgId,c.branchId,c.userId)}} satisfies ApiSuccessResponse<any>)}catch(e){next(e)}};
  listShifts = async (req: Request,res: Response,next: NextFunction)=>{try{const c=ctx(req);res.json({success:true,data:await shiftRepository.listShifts(c.orgId,c.branchId,{cashierId:req.query.cashierId?Number(req.query.cashierId):undefined,registerId:req.query.registerId?Number(req.query.registerId):undefined,status:req.query.status as string|undefined,from:req.query.from as string|undefined,to:req.query.to as string|undefined})} satisfies ApiSuccessResponse<any>)}catch(e){next(e)}};
  getShift = async (req: Request,res: Response,next: NextFunction)=>{try{const c=ctx(req);const id=Number(req.params.id);if(!Number.isInteger(id))throw new BadRequestError('Valid shift ID is required','INVALID_SHIFT_ID');const shift=await shiftRepository.getShift(id,c.orgId,c.branchId);if(!shift)throw new BadRequestError('Shift not found','SHIFT_NOT_FOUND');res.json({success:true,data:shift} satisfies ApiSuccessResponse<any>)}catch(e){next(e)}};
  openShift = async (req: Request,res: Response,next: NextFunction)=>{try{const c=ctx(req);const shift=await shiftRepository.openShift(c.orgId,c.branchId,c.userId,Number(req.body.registerId),Number(req.body.openingCash),req.body.notes);realtimePublisher.publish({type:'shift.opened',organizationId:c.orgId,branchId:c.branchId,entityType:'shift',entityId:shift.id,data:{registerId:shift.registerId,status:shift.status,openingCash:shift.openingCash}});res.status(201).json({success:true,data:shift} satisfies ApiSuccessResponse<any>)}catch(e){next(e)}};
  closeShift = async (req: Request,res: Response,next: NextFunction)=>{try{const c=ctx(req);const id=Number(req.params.id);if(!Number.isInteger(id))throw new BadRequestError('Valid shift ID is required','INVALID_SHIFT_ID');const shift=await shiftRepository.closeShift(id,c.orgId,c.branchId,c.userId,Number(req.body.countedCash),req.body.notes);realtimePublisher.publish({type:'shift.closed',organizationId:c.orgId,branchId:c.branchId,entityType:'shift',entityId:shift.id,data:{registerId:shift.registerId,status:shift.status,variance:shift.variance}});res.json({success:true,data:shift} satisfies ApiSuccessResponse<any>)}catch(e){next(e)}};
  summary = async (req: Request,res: Response,next: NextFunction)=>{try{const c=ctx(req);const id=Number(req.params.id);if(!Number.isInteger(id))throw new BadRequestError('Valid shift ID is required','INVALID_SHIFT_ID');res.json({success:true,data:await shiftRepository.shiftSummary(id,c.orgId,c.branchId)} satisfies ApiSuccessResponse<any>)}catch(e){next(e)}};
  listMovements = async (req: Request,res: Response,next: NextFunction)=>{try{const c=ctx(req);const id=Number(req.params.id);if(!Number.isInteger(id))throw new BadRequestError('Valid shift ID is required','INVALID_SHIFT_ID');res.json({success:true,data:await shiftRepository.listCashMovements(id,c.orgId,c.branchId)} satisfies ApiSuccessResponse<any>)}catch(e){next(e)}};
  addMovement = async (req: Request,res: Response,next: NextFunction)=>{try{const c=ctx(req);const id=Number(req.params.id);if(!Number.isInteger(id))throw new BadRequestError('Valid shift ID is required','INVALID_SHIFT_ID');const movement=await shiftRepository.addCashMovement(id,c.orgId,c.branchId,c.userId,req.body);realtimePublisher.publish({type:'cash_movement.created',organizationId:c.orgId,branchId:c.branchId,entityType:'cash_movement',entityId:movement.id,data:{shiftId:id,type:movement.movementType,amount:movement.amount}});res.status(201).json({success:true,data:movement} satisfies ApiSuccessResponse<any>)}catch(e){next(e)}};
}
export const shiftController = new ShiftController();
