import {createHash} from 'node:crypto';
import {Request,Response,NextFunction} from 'express';
import {ApiSuccessResponse} from '../../shared/types'; import {BadRequestError,ForbiddenError} from '../../shared/errors'; import {purchasingRepository} from './repository';
const ctx=(req:Request)=>{if(!req.user?.organizationId)throw new ForbiddenError('Authenticated tenant context is missing','MISSING_TENANT_CONTEXT');if(!req.user.activeBranchId)throw new ForbiddenError('Active branch context is missing','MISSING_BRANCH_CONTEXT');return {org:req.user.organizationId,branch:req.user.activeBranchId,user:req.user.id};};
const id=(v:any)=>{const n=Number(v);if(!Number.isInteger(n)||n<=0)throw new BadRequestError('Invalid id','INVALID_ID');return n;};
export class PurchasingController{
 suppliers=async(req:Request,res:Response,next:NextFunction)=>{try{const c=ctx(req);res.json({success:true,data:await purchasingRepository.listSuppliers(c.org)} satisfies ApiSuccessResponse<any>)}catch(e){next(e)}};
 createSupplier=async(req:Request,res:Response,next:NextFunction)=>{try{const c=ctx(req);res.status(201).json({success:true,data:await purchasingRepository.createSupplier(c.org,req.body)} satisfies ApiSuccessResponse<any>)}catch(e){next(e)}};
 updateSupplier=async(req:Request,res:Response,next:NextFunction)=>{try{const c=ctx(req);res.json({success:true,data:await purchasingRepository.updateSupplier(c.org,id(req.params.id),req.body)} satisfies ApiSuccessResponse<any>)}catch(e){next(e)}};
 supplierItems=async(req:Request,res:Response,next:NextFunction)=>{try{const c=ctx(req);res.json({success:true,data:await purchasingRepository.supplierItems(c.org,c.branch,id(req.params.id))} satisfies ApiSuccessResponse<any>)}catch(e){next(e)}};
 upsertSupplierItem=async(req:Request,res:Response,next:NextFunction)=>{try{const c=ctx(req);res.status(200).json({success:true,data:await purchasingRepository.upsertSupplierItem(c.org,c.branch,id(req.params.id),req.body)} satisfies ApiSuccessResponse<any>)}catch(e){next(e)}};
 purchaseOrders=async(req:Request,res:Response,next:NextFunction)=>{try{const c=ctx(req);res.json({success:true,data:await purchasingRepository.listPOs(c.org,c.branch,req.query)} satisfies ApiSuccessResponse<any>)}catch(e){next(e)}};
 createPO=async(req:Request,res:Response,next:NextFunction)=>{try{const c=ctx(req);res.status(201).json({success:true,data:await purchasingRepository.createPO(c.org,c.branch,c.user,req.body)} satisfies ApiSuccessResponse<any>)}catch(e){next(e)}};
 getPO=async(req:Request,res:Response,next:NextFunction)=>{try{const c=ctx(req);res.json({success:true,data:await purchasingRepository.getPO(c.org,c.branch,id(req.params.id))} satisfies ApiSuccessResponse<any>)}catch(e){next(e)}};
 transition=(target:string)=>(async(req:Request,res:Response,next:NextFunction)=>{try{const c=ctx(req);res.json({success:true,data:await purchasingRepository.transition(c.org,c.branch,c.user,id(req.params.id),target)} satisfies ApiSuccessResponse<any>)}catch(e){next(e)}});
 receive=async(req:Request,res:Response,next:NextFunction)=>{try{const c=ctx(req);const key=String(req.header('Idempotency-Key')||'').trim();if(!key)throw new BadRequestError('Idempotency-Key header is required for receiving','IDEMPOTENCY_KEY_REQUIRED');if(key.length<8||key.length>100||!/^[A-Za-z0-9._:-]+$/.test(key))throw new BadRequestError('Invalid Idempotency-Key header','INVALID_IDEMPOTENCY_KEY');const poId=id(req.params.id);const hash=createHash('sha256').update(JSON.stringify({poId,...req.body})).digest('hex');res.status(201).json({success:true,data:await purchasingRepository.receive(c.org,c.branch,c.user,poId,req.body,key,hash)} satisfies ApiSuccessResponse<any>)}catch(e){next(e)}};
}
export const purchasingController=new PurchasingController();
